
// This file was auto-generated by ML.NET Model Builder. 

using FullCroppedClassificationModel_ConsoleApp1;
using System.IO;

// Create single instance of sample data from first line of dataset for model input
var imageBytes = File.ReadAllBytes(@"D:\ML\CroppedMulti\Empty\1134_350_sochi.camera_Торговая галерея 1_25_01.03.2024_13.17.25.png");
FullCroppedClassificationModel.ModelInput sampleData = new FullCroppedClassificationModel.ModelInput()
{
    ImageSource = imageBytes,
};

// Make a single prediction on the sample data and print results.
var sortedScoresWithLabel = FullCroppedClassificationModel.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}
